config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :search_analytics, only: [:index] do
    get :results, on: :collection
  end
  
  resources :articles
  get "up" => "rails/health#show", as: :rails_health_check

  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/search_analytic.rb
class SearchAnalytic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    query = params[:search]
    if (query.present?)
      @articles = Article.where("title LIKE ?", "%#{params[:search]}%")
      user_key = "User:#{current_user.email}"
      timed_query = "#{query}:#{DateTime.now.to_i}"

      Rails.cache.write(user_key, timed_query)

    else
      @articles = Article.all
    end

    respond_to do |format|
      format.html do
        if request.xhr?
          render partial: "articles", locals: { articles: @articles }
        else
          render :index
        end
      end
    end
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/search_analytics_controller.rb
class SearchAnalyticsController < ApplicationController
  before_action :set_search_analytic, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    SearchAnalyticJob.perform_async
  end

  def results 
    analytics = Rails.cache.read("search_analytics")
    if analytics
      render json: {status: :ok, analytics: analytics}
    else
      render json: {status: :processing, status: :accepted}
    end
  end

  def show
  end

  def new
    @search_analytic = SearchAnalytic.new
  end

  def edit
  end

  def create
    @search_analytic = SearchAnalytic.new(search_analytic_params)

    respond_to do |format|
      if @search_analytic.save
        format.html { redirect_to search_analytic_url(@search_analytic), notice: "Search analytic was successfully created." }
        format.json { render :show, status: :created, location: @search_analytic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @search_analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @search_analytic.update(search_analytic_params)
        format.html { redirect_to search_analytic_url(@search_analytic), notice: "Search analytic was successfully updated." }
        format.json { render :show, status: :ok, location: @search_analytic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @search_analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @search_analytic.destroy!

    respond_to do |format|
      format.html { redirect_to search_analytics_url, notice: "Search analytic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_search_analytic
      @search_analytic = SearchAnalytic.find(params[:id])
    end

    def search_analytic_params
      params.require(:search_analytic).permit(:ip_address, :query)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_analytics_helper.rb
module SearchAnalyticsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= article.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= article.body %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this article", article, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this article", edit_article_path(article), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles" do %>
  <div id="articles" class="min-w-full" data-article-search-target="articles">
    <%= render @articles %>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article, class: "contents") do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing article</h1>

  <%= render "form", article: @article %>

  <%= link_to "Show this article", @article, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/articles/index.html.erb
<div class="w-full" data-controller="article-search">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Articles</h1>
    <%= link_to "New article", new_article_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>

    
    </div>
    <%= form_with(url: articles_path, method: "get", id: "articleSearchForm", data: {article_search_target: "form" }, class: "") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search", id: "articleSearchInput", data: {article_search_target: "input"} %>
    <% end %>

  <div id="articles" class="min-w-full" data-article-search-target="articles">
    <%= render "articles", articles: @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New article</h1>

  <%= render "form", article: @article %>

  <%= link_to "Back to articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/articles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @article %>

    <%= link_to "Edit this article", edit_article_path(@article), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this article", article_path(@article), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="flex justify-between items-center gap-8 bg-blue-50 py-4 px-4 shadow-md">
        <section></section>
        <section class="flex justify-center items-center gap-8">
          <a href="/">Home</a>
          <a href="/search_analytics">Analytics</a>
        </section>
        <section>
          <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
        </section>
      </nav>
      <% end %>
      <main class="container mx-auto px-8 py-8 flex">
        <%= yield %>
      </main>
  </body>
</html>

app/views/search_analytics/_form.html.erb
<%= form_with(model: search_analytic, class: "contents") do |form| %>
  <% if search_analytic.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(search_analytic.errors.count, "error") %> prohibited this search_analytic from being saved:</h2>

      <ul>
        <% search_analytic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :ip_address %>
    <%= form.text_field :ip_address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :query %>
    <%= form.text_field :query, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/search_analytics/_search_analytic.html.erb
<div id="<%= dom_id search_analytic %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= search_analytic.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Query:</strong>
    <%= search_analytic.query %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Count:</strong>
    <%= search_analytic.count %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this search analytic", search_analytic, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this search analytic", edit_search_analytic_path(search_analytic), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/search_analytics/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing search analytic</h1>

  <%= render "form", search_analytic: @search_analytic %>

  <%= link_to "Show this search analytic", @search_analytic, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to search analytics", search_analytics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/search_analytics/index.html.erb
<div class="w-full" data-controller="analytics">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl mb-12">Search Analytics</h1>
  </div>

  <div id="search_analytics" data-analytics-target="output" class="min-w-full grid gap-8">
    <div class="flex justify-center items-center w-full">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width={24}
        height={24}
        fill="none"
        class="block h-6 w-6"
      >
        <path
          fill="#73B12C"
          d="M5.656 19.732a9.996 9.996 0 0 0 4.613 2.12l.143-2.012a7.969 7.969 0 0 1-3.334-1.53l-1.422 1.422Z"
        />
        <path
          fill="#71AF29"
          d="M4.043 13H2.025a9.94 9.94 0 0 0 2.217 5.318l1.42-1.42A7.976 7.976 0 0 1 4.042 13Z"
        />
        <path
          fill="#81B841"
          d="m16.83 18.34 1.011 1.734a10.107 10.107 0 0 0 2.135-2.107l-1.73-1.037a8.038 8.038 0 0 1-1.416 1.41Z"
        />
        <path
          fill="#8EC74C"
          d="m12.406 19.98-.142 2.006a9.93 9.93 0 0 0 3.851-.904l-1.01-1.73a7.976 7.976 0 0 1-2.699.628Z"
        />
        <path
          fill="#088242"
          d="M19.906 11h2.017c-.504-5.046-4.773-9-9.949-9s-9.446 3.954-9.949 9h2.018c.495-3.94 3.86-7 7.931-7 4.072 0 7.437 3.06 7.932 7Z"
        />
      </svg>
    </div>
  </div>
</div>

app/views/search_analytics/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New search analytic</h1>

  <%= render "form", search_analytic: @search_analytic %>

  <%= link_to "Back to search analytics", search_analytics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/search_analytics/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @search_analytic %>

    <%= link_to "Edit this search_analytic", edit_search_analytic_path(@search_analytic), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this search_analytic", search_analytic_path(@search_analytic), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to search_analytics", search_analytics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>